# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a5e2a795859cdd7e823aac1c00f2a9222283831379a3c315d3d711389993b3e5e683258072577a2adf8c6f10362d2419b829e603ffd3720d1da60d6ecb62de

test:
  secret_key_base: d9d907f3ac41e35cabbf2f0a38eed128bc13e7d7f8c5c7e9e6ca4de6df53c4d35d09cf304bc752818fd094bba931540d3f401e6c3463dd9489b6bc1dac364973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
